client_config_backend: file
client_config:
    client_id: 837586755304-r1tgrecs430gl8iredjh5bstdv13a97n.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install
